batch_size: 32
data_path: data/aishell_ner
deterministic: true
epoch_num: 50
generate_hyper:
  num_beams: 5
  num_return_sequences: 1
  output_scores: true
gpu_device:
- 1
learning_rate: 0.0005
log_every_n_steps: 30
max_length: 50
model_name_or_path: cache/bart-large
precision: bf16-mixed
seed: 42
wandb_project_name: Seq2seqbaseline
wandbdescription: null
warmup_rate: 0.1
